version: 2

sources:
  - name: properties
    description: <markdown_string>
    database: DEVELOPER_DB
    schema: TIRUPATHIRAO_SCHEMA
    tables:
      - name: US_ACCIDENT_INCREMENTAL_LOAD
      - name: US_ACCIDENT_CONVERT_DATE